name: Build and Publish Game (Windows + macOS)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile --windowed main.py

      - name: Prepare latest-apps folder
        run: |
          mkdir -p latest-apps
          if [ "$RUNNER_OS" == "Windows" ]; then
            powershell Copy-Item dist\* latest-apps\ -Recurse -Force
          else
            cp dist/* latest-apps/
          fi

      - name: Commit and push builds
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add latest-apps
          git commit -m "Update latest builds (${{ runner.os }})" || echo "No changes to commit"
          git push
